output_directory: data
point_size: 3.0
viewport_background: '#000000'
bounding_box_color_mode: single
bounding_box_color: '#AA55FF'
bounding_box_line_width: 3.0
bounding_box_show_id: true
mesh_render_mode: wireframe
mesh_elevation_colormap: plasma
mesh_smooth_normals: true
